#+OPTIONS: H:3 num:nil toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS: author:nil email:nil creator:nil timestamp:nil
#+TITLE: Emacs init file written in org-mode
#+STARTUP: indent
#+SETUPFILE: ~/org/org-templates/level-1.org
#+LANGUAGE: en
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_HEAD: <link rel="stylesheet" title="Standard" href="../css/worg.css" type="text/css" />
#+HTML_HEAD: <script type="text/javascript"><?php include ("libjs/layersmenu-browser_detection.js"); ?></script>
#+HTML_HEAD: <link rel="stylesheet" href="../layerstreemenu.css" type="text/css"></link>
#+HTML_HEAD: <script type="text/javascript" src="libjs/layerstreemenu-cookies.js"></script>
#+XSLT: 

#+LANGUAGE: en

This file is my =.emacs= configuration file (more precisely my
=~/.emacs.d/init.el= configuration). I stole it from [[http://mescal.imag.fr/membres/arnaud.legrand/misc/init.php][here].


* Installation
Copy it into =~/.emacs.d/init.org=. 

You should consider installing xclip (=sudo apt-get install xclip= in a
shell and =M-x package-install= the =xclip= package within emacs) as
it will ease interactions with emacs when running in a terminal.

Then do =M-x org-babel-load-file= (=M-x= means pressing =Alt= and =x=
simultaneously to get the emacs prompt that allows you to call emacs
functions, also remember you can press =Tab= to activate auto
completion) and provide =~/.emacs.d/init.org=. This should evaluate
every piece of emacs-lisp code available here.

Next time, simply reload changes with "C-c i". If some stuff does not
work (in particular in the org-mode website generation section or in
the tabs section), just comment them and proceed.
* MELPA
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
;;(when (< emacs-major-version 24)
;; For important compatibility libraries like cl-lib
;;  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
#+END_SRC

* Face
** eliminate noise
*** disable startup message
#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t)
#+END_SRC
*** remove the noisy from scratch buffer
#+BEGIN_SRC emacs-lisp
(setq initial-scratch-message nil)
#+END_SRC
** stop syntax highlight
#+BEGIN_SRC emacs-lisp
;;(global-font-lock-mode 0)
#+END_SRC
** startup with window split
#+BEGIN_SRC emacs-lisp
;;(split-window-right)
#+END_SRC
** Change frame name of emacs:
#+BEGIN_SRC emacs-lisp
(setq frame-title-format
  '("Emacs - " (buffer-file-name "%f"
    (dired-directory dired-directory "%b"))))
#+END_SRC
[16:29:40; 24.04.2013]
** Line and column numbering
#+BEGIN_SRC emacs-lisp
(line-number-mode 1)
(column-number-mode 1)
#+END_SRC
** Parenthesis
#+BEGIN_SRC emacs-lisp
(load-library "paren")
(show-paren-mode 1)
(transient-mark-mode t)
(require 'paren)
#+END_SRC
** Stop blinking the cursor
#+BEGIN_SRC emacs-lisp
;;(blink-cursor-mode 0)
#+END_SRC
** disable scroll/menu/tool bar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
;;(menu-bar-mode 0)
(tool-bar-mode 0)
#+END_SRC
** highlight matches from searches
#+BEGIN_SRC emacs-lisp
(setq isearch-highlight t)
(setq search-highlight t)
(setq query-replace-highlight t)
#+END_SRC
** replace highlighted text with what I type rather than just inserting at a point
#+BEGIN_SRC emacs-lisp
(delete-selection-mode t)
#+END_SRC
** transparent
#+BEGIN_SRC emacs-lisp
;;(set-frame-parameter (selected-frame) 'alpha '(85 50))
#+END_SRC
** add a newline character at the end of the file
#+BEGIN_SRC emacs-lisp
(setq require-final-newline t)
#+END_SRC
** always replace tabs with spaces and set tab width to 4
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
#+END_SRC
** display the linenumber in the margin area
#+BEGIN_SRC emacs-lisp
;;(global-linum-mode t)
;;(setq linum-format "%d ")
#+END_SRC
** highlight the current line
#+BEGIN_SRC emacs-lisp
(global-hl-line-mode t)
#+END_SRC
** always display an indicator for empty lines in the margin area
#+BEGIN_SRC emacs-lisp
(setq-default indicate-empty-lines t)
#+END_SRC

** highlight column with column marker
#+BEGIN_SRC emacs-lisp
(require 'column-marker)
#+END_SRC
* Backup
back files to tmp and keep one week old backups
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))
(message "Deleting old backup files...")
(let ((week (* 60 60 24 7))
      (current (float-time (current-time))))
  (dolist (file (directory-files temporary-file-directory t))
    (when (and (backup-file-name-p file)
               (> (- current (float-time (nth 5 (file-attributes file))))
                  week))
      (message "%s" file)
      (delete-file file))))
#+END_SRC
* Color Theme
** change the back/fore ground only
#+BEGIN_SRC emacs-lisp
;;(add-to-list 'default-frame-alist '(background-color . "black"))
;;(add-to-list 'default-frame-alist '(foreground-color . "white"))
;;(set-face-background hl-line-face "#000020")
#+END_SRC
** use pre-defined theme
#+BEGIN_SRC emacs-lisp
;;(add-to-list 'custom-theme-load-path "~/.emacs.d/site-lisp")
(when (display-graphic-p)
	(load-theme 'misterioso t))
#+END_SRC
* Shortcuts:
** Load emacs initialization file:
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c i") 
(lambda() (interactive)(org-babel-load-file "~/.emacs.d/init.org")))
#+END_SRC
[16:28:10; 24.04.2013]
** UTF 8 by default
#+BEGIN_SRC emacs-lisp
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+END_SRC
** Keyboard fix for Mac OS X users...
Thanks to Adrien Lebre for providing me with this
=ns-use-mac-modifier-symbols= thing. Unfortunately, this is broken at
the moment (I tried to wrap the command around the cond but it should
fail on mac). 
#+BEGIN_SRC emacs-lisp
(cond
 ((string-equal system-type "darwin")   ; Mac OS X
  (progn
    (setq
     ns-command-modifier 'meta         ; Apple/Command key is Meta
	 ns-alternate-modifier nil         ; Option is the Mac Option key
	 ns-use-mac-modifier-symbols  nil  ; display standard Emacs (and not standard Mac) modifier symbols
	 ))
  )
 )
#+END_SRC
** Navigate back in text
#+BEGIN_SRC emacs-lisp
(defun jump-mark ()
  (interactive)
  (set-mark-command (point)))
(defun beginning-of-defun-and-mark ()
  (interactive)
  (push-mark (point))
  (beginning-of-defun))
(defun end-of-defun-and-mark ()
  (interactive)
  (push-mark (point))
  (end-of-defun))

(global-set-key "\^c\^b" 'beginning-of-defun-and-mark)
(global-set-key "\^c\^e" 'end-of-defun-and-mark)
(global-set-key "\^c\^j" 'jump-mark)
(global-set-key [S-f6] 'jump-mark)		;; jump from mark to mark
#+END_SRC
** Use X clipboard (cut'n paste)
Since I switched to emacs 24, cutting and pasting to emacs has
become burdensome. For example, I had to do S-C-c after selecting
terminals areas before being able to copy in emacs. With the
following commants, I don't have to do this anymore. I wish it
would have eased interactions when running emacs in a terminal
(i.e., with =-nw=) but it does not. :( [[http://stackoverflow.com/questions/13036155/how-to-to-combine-emacs-primary-clipboard-copy-and-paste-behavior-on-ms-windows]]
#+BEGIN_SRC emacs-lisp
(setq select-active-regions nil)
(setq x-select-enable-primary t)
(setq x-select-enable-clipboard t)
(setq mouse-drag-copy-region t)
#+END_SRC
** Cut'n paste in no-window mode
Despite what can be found in many old discussions on emacs mailing
lists, it seems to be possible and the trick is to use xclip!
[[http://stackoverflow.com/questions/4580835/emacs-copy-kill-ring-to-system-clipboard-in-nowindow-mode]]   [[http://stackoverflow.com/questions/5288213/how-can-i-paste-the-selected-region-outside-of-emacs/14659015#14659015]]

If you simply use the following commands, then emacs cut-n-paste works
just perfectly with the X clipboard. I can select in emacs no window
and then paste with the middle-click button! :) Many thanks to Vijay
for pointing me out that I had forgotten the "require" line... :)
#+BEGIN_SRC emacs-lisp
;;  (if(string-equal system-type "gnu/linux")   ; Linux!
;;      (
       (require (quote xclip))
       (xclip-mode 1)
;;      )()
;;        )
#+END_SRC
** Increase/decrease text size in emacs
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
;; C-x C-0 restores the default font size
#+END_SRC
[11:26:47; 18.04.2014]
** Add spell checker to the file
#+BEGIN_SRC emacs-lisp
;; Inspired from http://tex.stackexchange.com/questions/166681/changing-language-of-flyspell-emacs-with-a-shortcut
;; (defun spell (choice)
;;    "Switch between language dictionaries."
;;    (interactive "cChoose:  (a) American | (f) Francais")
;;     (cond ((eq choice ?1)
;;            (setq flyspell-default-dictionary "american")
;;            (setq ispell-dictionary "american")
;;            (ispell-kill-ispell))
;;           ((eq choice ?2)
;;            (setq flyspell-default-dictionary "francais")
;;            (setq ispell-dictionary "francais")
;;            (ispell-kill-ispell))
;;           (t (message "No changes have been made."))) )

(define-key global-map (kbd "C-c s a") (lambda () (interactive) (ispell-change-dictionary "american")))
(define-key global-map (kbd "C-c s f") (lambda () (interactive) (ispell-change-dictionary "francais")))
(define-key global-map (kbd "C-c s r") 'flyspell-region)
(define-key global-map (kbd "C-c s b") 'flyspell-buffer)
(define-key global-map (kbd "C-c s s") 'flyspell-mode)
#+END_SRC
* Org-mode + babel:
** .org file will be opened with org-mode
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
#+end_src
** todo.org
#+begin_src emacs-lisp
(custom-set-variables
 '(org-agenda-files (quote ("~/todo.org"))))
#+end_src
** export option for beamer
#+begin_src emacs-lisp
(require 'ox-latex)
(add-to-list 'org-latex-classes
             '("beamer"
               "\\documentclass\[presentation\]\{beamer\}"
               ("\\section\{%s\}" . "\\section*\{%s\}")
               ("\\subsection\{%s\}" . "\\subsection*\{%s\}")
               ("\\subsubsection\{%s\}" . "\\subsubsection*\{%s\}")))
#+end_src
** shortcuts
#+begin_src emacs-lisp
;;(setq org-ctrl-k-protect-subtree t)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cb" 'org-iswitchb)
#+end_src

** pretty format
*** Just the Italics
#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src
*** Better Bullets 
Asterisks and dashes for bullet lists are fine, but having an actual
circular bullet, is just nice: 
#+begin_src emacs-lisp
(font-lock-add-keywords 'org-mode 
			'(("^+\\([-*]\\) "
			   (0 (prog1 () (compose-region (match-beginning 1)(match-end 1) "•"))))))
#+end_src
*** Better Header Bullets
#+begin_src emacs-lisp
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src
*** Better Header fonts
#+begin_src emacs-lisp
;;(let* ((variable-tuple (cond ((x-list-fonts "Source Sans Pro") '(:font "Source Sans Pro"))
;;                             ((x-list-fonts "Lucida Grande")   '(:font "Lucida Grande"))
;;                             ((x-list-fonts "Verdana")         '(:font "Verdana"))
;;                             ((x-family-fonts "Sans Serif")    '(:family "Sans Serif"))
;;                             (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
;;       (headline           `(:inherit default :weight bold )))
;;
;;  (custom-theme-set-faces 'user
;;                          `(org-level-8 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-7 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-6 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-5 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-4 ((t (,@headline ,@variable-tuple :height 1.1))))
;;                          `(org-level-3 ((t (,@headline ,@variable-tuple :height 1.25))))
;;                          `(org-level-2 ((t (,@headline ,@variable-tuple :height 1.5))))
;;                          `(org-level-1 ((t (,@headline ,@variable-tuple :height 1.75))))
;;                          `(org-document-title ((t (,@headline ,@variable-tuple :height 1.5 :underline nil))))))
#+end_src
** Seamless use of babel (no confirmation, lazy export)
#+BEGIN_SRC emacs-lisp
(setq org-export-babel-evaluate nil)
(setq org-confirm-babel-evaluate nil)
#+END_SRC
** Some initial languages we want org-babel to support:
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (sh . t)
     (python . t)
     (R . t)
     (ruby . t)
     (ocaml . t)
     (ditaa . t)
     (dot . t)
     (octave . t)
     (sqlite . t)
     (perl . t)
     (screen . t)
     (plantuml . t)
     (lilypond . t)
     (org . t)
     (makefile . t)
     ))
  (setq org-src-preserve-indentation t)
#+END_SRC

** Adding source code blocks:
*** With capital letters:
To use this type <S and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("S" "#+begin_src ?\n\n#+end_src" "<src lang=\"?\">\n\n</src>"))
#+END_SRC

*** Emacs-elisp code:
To use this type <m and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("m" "#+begin_src emacs-lisp\n\n#+end_src" "<src lang=\"emacs-lisp\">\n\n</src>"))
#+END_SRC

*** R code:
To use this type <r and then TAB. This creates an R block for textual output.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("r" "#+begin_src R :results output :session *R* :exports both\n\n#+end_src" "<src lang=\"R\">\n\n</src>"))
#+END_SRC

To use this type <R and then TAB. This creates an R block for graphics
that are stored in the =/tmp/=.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("R" "#+begin_src R :results output graphics :file (org-babel-temp-file \"figure\" \".png\") :exports both :width 600 :height 400 :session *R* \n\n#+end_src" "<src lang=\"R\">\n\n</src>"))
#+END_SRC

To use this type <RR and then TAB. This creates an R block for
graphics that are stored in the directory of the current file.

#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("RR" "#+begin_src R :results output graphics :file  (org-babel-temp-file (concat (file-name-directory (or load-file-name buffer-file-name)) \"figure-\") \".png\") :exports both :width 600 :height 400 :session *R* \n\n#+end_src" "<src lang=\"R\">\n\n</src>"))
#+END_SRC

*** Python code
To use this type <p and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("p" "#+begin_src python :results output :exports both\n\n#+end_src" "<src lang=\"python\">\n\n</src>"))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("P" "#+begin_src python :results output :session *python* :exports both\n\n#+end_src" "<src lang=\"python\">\n\n</src>"))
#+END_SRC
*** Bash "sh" code:
To use this type <b and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("b" "#+begin_src sh :results output :exports both\n\n#+end_src" "<src lang=\"sh\">\n\n</src>"))
#+END_SRC

To use this type <B and then TAB. This comes with a session argument
(e.g., in case you want to keep ssh connexions open).
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("B" "#+begin_src sh :session foo :results output :exports both \n\n#+end_src" "<src lang=\"sh\">\n\n</src>"))
#+END_SRC

[18:23:44; 21.06.2013]
*** Graphviz
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("g" "#+begin_src dot :results output graphics :file \"/tmp/graph.pdf\" :exports both
   digraph G {
      node [color=black,fillcolor=white,shape=rectangle,style=filled,fontname=\"Helvetica\"];
      A[label=\"A\"]
      B[label=\"B\"]
      A->B
   }\n#+end_src" "<src lang=\"dot\">\n\n</src>"))
#+END_SRC
** Evaluating whole subtree:
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c S-t") 'org-babel-execute-subtree)
#+END_SRC

[15:25:16; 17.12.2013]
** Display images
#+BEGIN_SRC emacs-lisp
(add-hook 'org-babel-after-execute-hook 'org-display-inline-images) 
(add-hook 'org-mode-hook 'org-display-inline-images)
(add-hook 'org-mode-hook 'org-babel-result-hide-all)
#+END_SRC
* Eclim
#+BEGIN_SRC emacs-lisp
;;(custom-set-variables
;;  '(eclim-eclipse-dirs '("~/eclipse"))
;;  '(eclim-executable "~/eclipse/eclim")
;;  '(eclimd-executable "~/eclipse/eclimd"))
;;(require 'eclim)
;;(require 'eclimd)
;;(global-eclim-mode)
;;(setq help-at-pt-display-when-idle t)
;;(setq help-at-pt-timer-delay 0.1)
;;(help-at-pt-set-timer)
#+END_SRC
* Font(Chinese)
** use different font for English and Chinese
#+BEGIN_SRC emacs-lisp
;;(eval-when-compile (require 'cl))
;;
;;(defun set-font (english chinese english-size chinese-size)
;;(set-face-attribute 'default nil :font
;;(format "%s:pixelsize=%d" english english-size))
;;(dolist (charset '(kana han symbol cjk-misc bopomofo))
;;(set-fontset-font (frame-parameter nil 'font) charset
;;(font-spec :family chinese :size chinese-size))))
;;;;
;;;;(ecase system-type
;;;;(gnu/linux
;;(set-face-bold-p 'bold nil)
;;(set-face-underline-p 'bold nil)
;;(set-font "DejaVu Sans Mono" "Noto Sans Mono CJK SC" 15 14)
;;)
;;(darwin
;;(set-font "monofur" "STHeiti" 20 20)))
#+END_SRC
** use single font for all
#+BEGIN_SRC emacs-lisp
;;================================================================
;; use single font for all
;;================================================================
;;(set-face-attribute 'default nil :font "Noto Sans Mono CJK SC-13" )
(set-frame-font "DejaVu Sans Mono-11" nil t)
#+END_SRC
* GNUS
#+BEGIN_SRC emacs-lisp
;;(setq gnus-select-method
;;      '(nnimap "imap.exmail.qq.com"
;;               (nnimap-stream ssl)))
;;(setq send-mail-function    'smtpmail-send-it
;;      smtpmail-smtp-server  "smtp.exmail.qq.com"
;;      smtpmail-stream-type  'ssl
;;      smtpmail-smtp-service 465)
#+END_SRC

* Golang
** require lib
#+BEGIN_SRC emacs-lisp
(require 'go-mode-autoloads)
(require 'go-direx)
#+END_SRC
** golint like gofmt, but for checking style
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path (concat (getenv "GOPATH")  "/src/github.com/golang/lint/misc/emacs"))
(require 'golint)
#+END_SRC

** hook go-mode: goimports, gofmt, also some shorcuts for compile and navigation
#+BEGIN_SRC emacs-lisp
(add-hook 'go-mode-hook 
          (lambda()
            ;; tab size is 4
            (setq tab-width 4)
            (setq gofmt-command "goimports")
            (add-hook 'before-save-hook 'gofmt-before-save)
            ;; C-c c compile
            (setq compile-command "go generate && go build -v && go test -v && go vet")
            ;;(define-key go-mode-map "\C-cc" 'compile)
            (define-key go-mode-map "<f8>" 'compile)
            ;; C-c C-c 
            (define-key go-mode-map "\C-c\C-c" 'comment-region)
            ;; C-u C-c C-c 
            (define-key go-mode-map "\C-u\C-c\C-c" 'uncomment-region)
            (load-file (concat (getenv "GOPATH") "/src/golang.org/x/tools/cmd/oracle/oracle.el"))
            (define-key go-mode-map "<f5>" 'godef-jump)
            (define-key go-mode-map "<f6>" 'godef-jump-other-window)
            ))
#+END_SRC

** go-eldoc
#+BEGIN_SRC emacs-lisp
(require 'go-eldoc)
(add-hook 'go-mode-hook 'go-eldoc-setup)
(set-face-attribute 'eldoc-highlight-function-argument nil
                    :underline t :foreground "darkgreen"
                    :weight 'bold)
#+END_SRC
** Oracle
#+BEGIN_SRC emacs-lisp
;;(setq go-oracle-command "/usr/bin/oracle")
#+END_SRC
** go-rename
#+BEGIN_SRC emacs-lisp
(require 'go-rename)
#+END_SRC

** auto-complete
#+BEGIN_SRC emacs-lisp
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories (concat (getenv "GOPATH") "/src/github.com/auto-complete/auto-complete/dict"))
(require 'go-autocomplete)
(ac-config-default)
(ac-set-trigger-key "TAB")
#+END_SRC

** yasnippet
#+BEGIN_SRC emacs-lisp
(require 'yasnippet)
(add-to-list 'yas-snippet-dirs (concat (getenv "GOPATH") "/src/github.com/atotto/yasnippet-golang"))
(yas-reload-all)
(add-hook 'go-mode-hook #'yas-minor-mode)
;;(yas-global-mode 1)
#+END_SRC
** auto insert templete for go files
#+BEGIN_SRC emacs-lisp
(require 'autoinsert)
(setq auto-insert-directory "~/.emacs.d/_templates/")
(define-auto-insert "\\.go\\'" "T.go")
(define-auto-insert "\\test.go\\'" "T_test.go")
(add-hook 'find-file-hooks 'auto-insert)
#+END_SRC

* Helm
#+BEGIN_SRC emacs-lisp
;;(require 'helm-config)
;;(helm-mode 1)
;;
;;(global-set-key (kbd "M-x")                          'undefined)
;;(global-set-key (kbd "M-x")                          'helm-M-x)
;;(global-set-key (kbd "M-y")                          'helm-show-kill-ring)
;;(global-set-key (kbd "C-c f")                        'helm-recentf)
;;(global-set-key (kbd "C-x C-f")                      'helm-find-files)
;;(global-set-key (kbd "C-c <SPC>")                    'helm-all-mark-rings)
;;(global-set-key (kbd "C-x r b")                      'helm-filtered-bookmarks)
;;(global-set-key (kbd "C-h r")                        'helm-info-emacs)
;;(global-set-key (kbd "C-:")                          'helm-eval-expression-with-eldoc)
;;(global-set-key (kbd "C-,")                          'helm-calcul-expression)
;;(global-set-key (kbd "C-h i")                        'helm-info-at-point)
;;(global-set-key (kbd "C-x C-d")                      'helm-browse-project)
;;(global-set-key (kbd "<f1>")                         'helm-resume)
;;(global-set-key (kbd "C-h C-f")                      'helm-apropos)
;;(global-set-key (kbd "C-h a")                        'helm-apropos)
;;(global-set-key (kbd "<f5> s")                       'helm-find)
;;(global-set-key (kbd "<f2>")                         'helm-execute-kmacro)
;;(global-set-key (kbd "C-c g")                        'helm-gid)
;;(global-set-key (kbd "C-c i")                        'helm-imenu-in-all-buffers)
;;;;(global-set-key (kbd "<f11> o")                      'helm-org-agenda-files-headings)
;;(global-set-key (kbd "C-s")                          'helm-occur)
;;(define-key global-map [remap jump-to-register]      'helm-register)
;;(define-key global-map [remap list-buffers]          'helm-buffers-list)
;;(define-key global-map [remap dabbrev-expand]        'helm-dabbrev)
;;(define-key global-map [remap find-tag]              'helm-etags-select)
;;(define-key global-map [remap xref-find-definitions] 'helm-etags-select)
;;(define-key global-map (kbd "M-g a")                 'helm-do-grep-ag)
;;(define-key global-map (kbd "M-g g")                 'helm-grep-do-git-grep)
#+END_SRC
* Ido
#+BEGIN_SRC emacs-lisp
(ido-mode 1)
(ido-everywhere 1)
(require 'ido-ubiquitous)
(ido-ubiquitous-mode 1)
#+END_SRC
* Smex
#+BEGIN_SRC emacs-lisp
(smex-initialize)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
(require 'smex)
#+END_SRC
* Markdown
#+BEGIN_SRC emacs-lisp
(autoload 'markdown-mode "markdown-mode"
   "Major mode for editing Markdown files" t)
(add-to-list 'auto-mode-alist '("\\.text\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
#+END_SRC
* Python
** jedi
#+begin_src emacs-lisp
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)                 ; optional
#+end_src
* Auctex
#+begin_src emacs-lisp
;; auctex
;; (load "auctex.el" nil t t)
;; (load "preview-latex.el" nil t t)
;;(setq TeX-output-view-style
;;      (quote
;;       (("^pdf$" "." "evince -f %o")
;;        ("^html?$" "." "google-chrome-stable %o"))))
#+end_src
* Unicad is Awesome
#+begin_src emacs-lisp
(setq load-path
      (append (list "~/.emacs.d/site-lisp")
                      load-path))
(require 'unicad)
#+end_src
* Server Start
#+begin_src emacs-lisp
(server-start)
#+end_src
* auto-fill-mode for text files
#+begin_src emacs-lisp
(setq text-mode-hook '(lambda()  
                        (auto-fill-mode t) 
                        )) 
#+end_src
* ecb
#+begin_src emacs-lisp
;;'(require 'ecb-autoloads)
#+end_src
* jsp
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.jsp\\'" . html-mode))
#+end_src
* popwin
popwin to eliminate all these *help* *message* buffers
#+begin_src emacs-lisp
;;(require 'popwin)
;;(popwin-mode 1)
#+end_src
* jsx
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . jsx-mode))
(autoload 'jsx-mode "jsx-mode" "JSX mode" t)
#+end_src
* tramp
#+begin_src emacs-lisp
(setq tramp-default-method "ssh")
#+end_src
* json-reformat
#+begin_src emacs-lisp
(setq json-reformat:pretty-string? 1)
#+end_src
