#+OPTIONS: H:3 num:nil toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS: author:nil email:nil creator:nil timestamp:nil
#+TITLE: Emacs init file written in org-mode
#+STARTUP: indent
#+SETUPFILE: ~/org/org-templates/level-1.org
#+LANGUAGE: en
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_HEAD: <link rel="stylesheet" title="Standard" href="../css/worg.css" type="text/css" />
#+HTML_HEAD: <script type="text/javascript"><?php include ("libjs/layersmenu-browser_detection.js"); ?></script>
#+HTML_HEAD: <link rel="stylesheet" href="../layerstreemenu.css" type="text/css"></link>
#+HTML_HEAD: <script type="text/javascript" src="libjs/layerstreemenu-cookies.js"></script>
#+XSLT: 

#+LANGUAGE: en

This file is my =.emacs= configuration file (more precisely my
=~/.emacs.d/init.el= configuration). I stole it from [[http://mescal.imag.fr/membres/arnaud.legrand/misc/init.php][here]].


* Installation
Copy it into =~/.emacs.d/init.org=. 

You should consider installing xclip (=sudo apt-get install xclip= in a
shell and =M-x package-install= the =xclip= package within emacs) as
it will ease interactions with emacs when running in a terminal.

Then do =M-x org-babel-load-file= (=M-x= means pressing =Alt= and =x=
simultaneously to get the emacs prompt that allows you to call emacs
functions, also remember you can press =Tab= to activate auto
completion) and provide =~/.emacs.d/init.org=. This should evaluate
every piece of emacs-lisp code available here.

Next time, simply reload changes with "C-c i". If some stuff does not
work (in particular in the org-mode website generation section or in
the tabs section), just comment them and proceed.
* MELPA
#+BEGIN_SRC emacs-lisp
(require 'package)
;;(add-to-list 'package-archives
;;             '("melpa" . "https://melpa.org/packages/"))
(setq package-archives '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
                         ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
;;(when (< emacs-major-version 24)
;; For important compatibility libraries like cl-lib
;;  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
#+END_SRC

* Face
** show clock
#+BEGIN_SRC emacs-lisp
(display-time-mode 1)
#+END_SRC
** eliminate noise
*** disable startup message
#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t)
#+END_SRC
*** remove the noisy from scratch buffer and defautl to text-mode
#+BEGIN_SRC emacs-lisp
(setq initial-major-mode 'text-mode)
(setq initial-scratch-message nil)
#+END_SRC
** stop syntax highlight
#+BEGIN_SRC emacs-lisp
;;(global-font-lock-mode 0)
#+END_SRC
** startup with window split
#+BEGIN_SRC emacs-lisp
;;(split-window-right)
#+END_SRC
** Change frame name of emacs:
#+BEGIN_SRC emacs-lisp
(setq frame-title-format
  '("Emacs - " (buffer-file-name "%f"
    (dired-directory dired-directory "%b"))))
#+END_SRC
** Line and column numbering
#+BEGIN_SRC emacs-lisp
(line-number-mode 1)
(column-number-mode 1)
#+END_SRC
** Parenthesis
#+BEGIN_SRC emacs-lisp
(load-library "paren")
(show-paren-mode 1)
(transient-mark-mode t)
(require 'paren)
#+END_SRC
** Stop blinking the cursor
#+BEGIN_SRC emacs-lisp
;;(blink-cursor-mode 0)
#+END_SRC
** cursor color
#+BEGIN_SRC emacs-lisp
; Set cursor color to green
;;(set-cursor-color "#00ff00") 
#+END_SRC
** disable scroll/menu/tool bar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
(menu-bar-mode 0)
(tool-bar-mode 0)
#+END_SRC
** highlight matches from searches
#+BEGIN_SRC emacs-lisp
(setq isearch-highlight t)
(setq search-highlight t)
(setq query-replace-highlight t)
#+END_SRC
** replace highlighted text with what I type rather than just inserting at a point
#+BEGIN_SRC emacs-lisp
(delete-selection-mode t)
#+END_SRC
** transparent
#+BEGIN_SRC emacs-lisp
;;(set-frame-parameter (selected-frame) 'alpha '(85 50))
#+END_SRC
** add a newline character at the end of the file
#+BEGIN_SRC emacs-lisp
(setq require-final-newline t)
#+END_SRC
** always replace tabs with spaces and set tab width to 4
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
#+END_SRC
** display the linenumber in the margin area
#+BEGIN_SRC emacs-lisp
;;(global-linum-mode t)
;;(setq linum-format "%d ")
#+END_SRC
** highlight the current line
#+BEGIN_SRC emacs-lisp
;;(global-hl-line-mode t)
#+END_SRC
** always display an indicator for empty lines in the margin area
#+BEGIN_SRC emacs-lisp
(setq-default indicate-empty-lines t)
#+END_SRC
** highlight column with column marker
#+BEGIN_SRC emacs-lisp
;;(require 'column-marker)
#+END_SRC
** highlight todo
#+BEGIN_SRC emacs-lisp
(setq global-hl-todo-mode 1)
#+END_SRC
* Backup
back files to tmp and keep one week old backups
#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
;;(setq backup-directory-alist
;;      `((".*" . ,temporary-file-directory)))
;;(setq auto-save-file-name-transforms
;;      `((".*" ,temporary-file-directory t)))
;;(message "Deleting old backup files...")
;;(let ((week (* 60 60 24 7))
;;      (current (float-time (current-time))))
;;  (dolist (file (directory-files temporary-file-directory t))
;;    (when (and (backup-file-name-p file)
;;               (> (- current (float-time (nth 5 (file-attributes file))))
;;                  week))
;;      (message "%s" file)
;;      (delete-file file))))
#+END_SRC
* Color Theme
** change the back/forground only
#+BEGIN_SRC emacs-lisp
;;(add-to-list 'default-frame-alist '(background-color . "black"))
;;(add-to-list 'default-frame-alist '(foreground-color . "white"))
;;(set-face-background hl-line-face "#505050")
#+END_SRC
** use pre-defined theme
#+BEGIN_SRC emacs-lisp
(add-to-list 'custom-theme-load-path "~/.emacs.d/site-lisp")
(when (display-graphic-p)
	(load-theme 'wombat t))
#+END_SRC
** random theme
#+BEGIN_SRC emacs-lisp
;;(defun random-color-theme () (interactive)
;;  (let ((chosen-theme
;;         (nth
;;          (random
;;           (length (mapcar 'symbol-name (custom-available-themes))))
;;          (custom-available-themes))))
;;    (message "Theme: %s" chosen-theme)
;;    (load-theme chosen-theme t nil)))
;;
;;(defun show-me-the-colors ()  (interactive) (loop do (random-color-theme) (sit-for 3)))
;;(random-color-theme)
;;(setq color-theme-is-cumulative 'false)
#+END_SRC
* Shortcuts:
** Load emacs initialization file:
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c i") 
(lambda() (interactive)(org-babel-load-file "~/.emacs.d/init.org")))
#+END_SRC
** UTF 8 by default
#+BEGIN_SRC emacs-lisp
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+END_SRC
** Keyboard fix for Mac OS X users...
Thanks to Adrien Lebre for providing me with this
=ns-use-mac-modifier-symbols= thing. Unfortunately, this is broken at
the moment (I tried to wrap the command around the cond but it should
fail on mac). 
#+BEGIN_SRC emacs-lisp
(cond
 ((string-equal system-type "darwin")   ; Mac OS X
  (progn
    (setq
     ns-command-modifier 'meta         ; Apple/Command key is Meta
	 ns-alternate-modifier nil         ; Option is the Mac Option key
	 ns-use-mac-modifier-symbols  nil  ; display standard Emacs (and not standard Mac) modifier symbols
	 ))
  )
 )
#+END_SRC
** Navigate back in text
#+BEGIN_SRC emacs-lisp
(defun jump-mark ()
  (interactive)
  (set-mark-command (point)))
(defun beginning-of-defun-and-mark ()
  (interactive)
  (push-mark (point))
  (beginning-of-defun))
(defun end-of-defun-and-mark ()
  (interactive)
  (push-mark (point))
  (end-of-defun))

(global-set-key "\^c\^b" 'beginning-of-defun-and-mark)
(global-set-key "\^c\^e" 'end-of-defun-and-mark)
(global-set-key "\^c\^j" 'jump-mark)
(global-set-key [S-f6] 'jump-mark)		;; jump from mark to mark
#+END_SRC
** Increase/decrease text size in emacs
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
;; C-x C-0 restores the default font size
#+END_SRC
[11:26:47; 18.04.2014]
** neotree
#+BEGIN_SRC emacs-lisp
(global-set-key [f8] 'neotree-toggle)
#+END_SRC
* Org-mode + babel:
** .org file will be opened with org-mode
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
#+end_src
** todo.org
#+begin_src emacs-lisp
(custom-set-variables
 '(org-agenda-files (quote ("~/todo.org"))))
#+end_src
** track the DONE time
#+begin_src emacs-lisp
;;(setq org-log-done 'time)
#+end_src
** export option for beamer
#+begin_src emacs-lisp
(require 'ox-latex)
(add-to-list 'org-latex-classes
             '("beamer"
               "\\documentclass\[presentation\]\{beamer\}"
               ("\\section\{%s\}" . "\\section*\{%s\}")
               ("\\subsection\{%s\}" . "\\subsection*\{%s\}")
               ("\\subsubsection\{%s\}" . "\\subsubsection*\{%s\}")))
#+end_src
** shortcuts
#+begin_src emacs-lisp
;;(setq org-ctrl-k-protect-subtree t)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cb" 'org-iswitchb)
#+end_src

** pretty format
*** Just the Italics
#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src
*** Better Bullets 
Asterisks and dashes for bullet lists are fine, but having an actual
circular bullet, is just nice: 
#+begin_src emacs-lisp
(font-lock-add-keywords 'org-mode 
			'(("^+\\([-*]\\) "
			   (0 (prog1 () (compose-region (match-beginning 1)(match-end 1) "•"))))))
#+end_src
*** Better Header Bullets
#+begin_src emacs-lisp
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src
*** Better Header fonts
#+begin_src emacs-lisp
;;(let* ((variable-tuple (cond ((x-list-fonts "Source Sans Pro") '(:font "Source Sans Pro"))
;;                             ((x-list-fonts "Lucida Grande")   '(:font "Lucida Grande"))
;;                             ((x-list-fonts "Verdana")         '(:font "Verdana"))
;;                             ((x-family-fonts "Sans Serif")    '(:family "Sans Serif"))
;;                             (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
;;       (headline           `(:inherit default :weight bold )))
;;
;;  (custom-theme-set-faces 'user
;;                          `(org-level-8 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-7 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-6 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-5 ((t (,@headline ,@variable-tuple))))
;;                          `(org-level-4 ((t (,@headline ,@variable-tuple :height 1.1))))
;;                          `(org-level-3 ((t (,@headline ,@variable-tuple :height 1.25))))
;;                          `(org-level-2 ((t (,@headline ,@variable-tuple :height 1.5))))
;;                          `(org-level-1 ((t (,@headline ,@variable-tuple :height 1.75))))
;;                          `(org-document-title ((t (,@headline ,@variable-tuple :height 1.5 :underline nil))))))
#+end_src
** Seamless use of babel (no confirmation, lazy export)
#+BEGIN_SRC emacs-lisp
(setq org-export-babel-evaluate nil)
(setq org-confirm-babel-evaluate nil)
#+END_SRC
** Some initial languages we want org-babel to support:
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (sh . t)
     (python . t)
     (R . t)
     (ruby . t)
     (ocaml . t)
     (ditaa . t)
     (dot . t)
     (octave . t)
     (sqlite . t)
     (perl . t)
     (screen . t)
     (plantuml . t)
     (lilypond . t)
     (org . t)
     (makefile . t)
     ))
  (setq org-src-preserve-indentation t)
#+END_SRC

** Adding source code blocks:
*** With capital letters:
To use this type <S and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("S" "#+begin_src ?\n\n#+end_src" "<src lang=\"?\">\n\n</src>"))
#+END_SRC

*** Emacs-elisp code:
To use this type <m and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("m" "#+begin_src emacs-lisp\n\n#+end_src" "<src lang=\"emacs-lisp\">\n\n</src>"))
#+END_SRC

*** Python code
To use this type <p and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("p" "#+begin_src python :results output :exports both\n\n#+end_src" "<src lang=\"python\">\n\n</src>"))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("P" "#+begin_src python :results output :session *python* :exports both\n\n#+end_src" "<src lang=\"python\">\n\n</src>"))
#+END_SRC
*** Bash "sh" code:
To use this type <b and then TAB
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("b" "#+begin_src sh :results output :exports both\n\n#+end_src" "<src lang=\"sh\">\n\n</src>"))
#+END_SRC

To use this type <B and then TAB. This comes with a session argument
(e.g., in case you want to keep ssh connexions open).
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
        '("B" "#+begin_src sh :session foo :results output :exports both \n\n#+end_src" "<src lang=\"sh\">\n\n</src>"))
#+END_SRC

** Evaluating whole subtree:
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c S-t") 'org-babel-execute-subtree)
#+END_SRC

** Display images
#+BEGIN_SRC emacs-lisp
(add-hook 'org-babel-after-execute-hook 'org-display-inline-images) 
(add-hook 'org-mode-hook 'org-display-inline-images)
(add-hook 'org-mode-hook 'org-babel-result-hide-all)
#+END_SRC
* Font(Chinese)
** use different font for English and Chinese
#+BEGIN_SRC emacs-lisp
(eval-when-compile (require 'cl))

(defun set-font (english chinese english-size chinese-size)
    (set-face-attribute 'default nil :font
        (format "%s-%d" english english-size))
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset
            (font-spec :family chinese :size chinese-size))))

(ecase system-type
    (gnu/linux
        (set-face-bold-p 'bold nil)
        (set-face-underline-p 'bold nil)
        (set-font "Menlo" "SimSun" 14 16))
    (darwin
        (set-font "monofur" "STHeiti" 20 20)))
#+END_SRC
** use single font for all
#+BEGIN_SRC emacs-lisp
;;================================================================
;; use single font for all
;;================================================================
;;(add-to-list 'default-frame-alist
;;    '(font . "Menlo-10.5"))
;;(custom-set-faces
;;'(default ((t (:family "Menlo" :slant normal :weight regular :height 105 :width normal)))))
;; '(cursor ((t (:background "light gray" :foreground "pale green")))))
#+END_SRC
** chinese font setup
#+BEGIN_SRC emacs-lisp
;;(require 'chinese-fonts-setup)
;; 让 chinese-fonts-setup 随着 emacs 自动生效。
;;(chinese-fonts-setup-enable)
#+END_SRC
* GNUS
#+BEGIN_SRC emacs-lisp
;;(setq gnus-select-method
;;      '(nnimap "imap.exmail.qq.com"
;;               (nnimap-stream ssl)))
;;(setq send-mail-function    'smtpmail-send-it
;;      smtpmail-smtp-server  "smtp.exmail.qq.com"
;;      smtpmail-stream-type  'ssl
;;      smtpmail-smtp-service 465)
#+END_SRC

* Helm
#+BEGIN_SRC emacs-lisp
(require 'helm-config)
(helm-mode 1)
;;
(global-set-key (kbd "M-x")                          'helm-M-x)
(global-set-key (kbd "C-x C-f")                      'helm-find-files)
(global-set-key (kbd "C-x b")                      'helm-mini)
;; auto resize the completion window based on the candidates number
;;(helm-autoresize-mode 1)
#+END_SRC
* Markdown
#+BEGIN_SRC emacs-lisp
(autoload 'markdown-mode "markdown-mode"
   "Major mode for editing Markdown files" t)
(add-to-list 'auto-mode-alist '("\\.text\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
#+END_SRC
* Unicad is Awesome
#+begin_src emacs-lisp
(setq load-path
      (append (list "~/.emacs.d/site-lisp")
                      load-path))
(require 'unicad)
#+end_src
* Server Start
#+begin_src emacs-lisp
(server-start)
#+end_src
* tramp
#+begin_src emacs-lisp
(setq tramp-default-method "ssh")
#+end_src
* mu4e
#+begin_src emacs-lisp
(require 'mu4e)

;; default
(setq mu4e-maildir (expand-file-name "~/mail"))

;;(setq mu4e-drafts-folder "/[Gmail].Drafts")
;;(setq mu4e-sent-folder   "/[Gmail].Sent Mail")
;;(setq mu4e-trash-folder  "/[Gmail].Trash")

;; don't save message to Sent Messages, GMail/IMAP will take care of this
;;(setq mu4e-sent-messages-behavior 'delete)

;; setup some handy shortcuts
;;(setq mu4e-maildir-shortcuts
;;      '(("/INBOX"             . ?i)
;;        ("/[Gmail].Sent Mail" . ?s)
;;        ("/[Gmail].Trash"     . ?t)))

;; allow for updating mail using 'U' in the main view:
(setq mu4e-get-mail-command "getmail")

;; something about ourselves
;; I don't use a signature...
(setq
 user-mail-address "wanjing@creditx.com"
 user-full-name  "万晶"
 ;; message-signature
 ;;  (concat
 ;;    "Foo X. Bar\n"
 ;;    "http://www.example.com\n")
)

;; sending mail -- replace USERNAME with your gmail username
;; also, make sure the gnutls command line utils are installed
;; package 'gnutls-bin' in Debian/Ubuntu, 'gnutls' in Archlinux.

(require 'smtpmail)

(setq message-send-mail-function 'smtpmail-send-it
      smtpmail-smtp-server "smtp.exmail.qq.com"
      smtpmail-stream-type 'ssl
      smtpmail-smtp-service 465
)
#+end_src

* Chinese calendar
#+begin_src emacs-lisp
(require 'cal-china-x)
(setq mark-holidays-in-calendar t)
(setq cal-china-x-important-holidays cal-china-x-chinese-holidays)
(setq calendar-holidays cal-china-x-important-holidays)
#+end_src
* Wubi input method
#+begin_src emacs-lisp
(autoload 'chinese-wbim-use-package "chinese-wbim" "Another emacs input method")
;; Tooltip 暂时还不好用
(setq chinese-wbim-use-tooltip nil)

(register-input-method
 "chinese-wbim" "euc-cn" 'chinese-wbim-use-package
 "五笔" "汉字五笔输入法" "wb.txt")

;; 用 ; 暂时输入英文
(require 'chinese-wbim-extra)
(global-set-key ";" 'chinese-wbim-insert-ascii)

;设置默认输入法
(setq default-input-method 'chinese-wbim)
#+end_src

* Golang
** gopkg path
#+begin_src emacs-lisp
(defvar GO_PKG_PATH "/home/wanjing/gopkg")
(setenv "PATH" (concat (getenv "PATH") ":" GO_PKG_PATH "/bin"))
(setq exec-path (cons (concat GO_PKG_PATH "/bin") exec-path ))
#+end_src
** require lib
#+BEGIN_SRC emacs-lisp
(require 'go-mode)
(require 'go-direx)
#+END_SRC
** golint like gofmt, but for checking style
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path (concat GO_PKG_PATH "/src/github.com/golang/lint/misc/emacs"))
(require 'golint)
#+END_SRC

** hook go-mode: goimports, gofmt, also some shorcuts for compile and navigation
#+BEGIN_SRC emacs-lisp
(add-hook 'go-mode-hook 
          (lambda()
            ;; tab size is 4
            (setq tab-width 4)
            (setq gofmt-command "goimports")
            (add-hook 'before-save-hook 'gofmt-before-save)
            ;; C-c c compile
            (setq compile-command "go build -v && go vet")
            (define-key go-mode-map "\C-cc" 'compile)
            ;; C-c C-c 
            (define-key go-mode-map "\C-c\C-c" 'comment-region)
            ;; C-u C-c C-c 
            (define-key go-mode-map "\C-u\C-c\C-c" 'uncomment-region)
            ))
#+END_SRC

** go-eldoc
#+BEGIN_SRC emacs-lisp
(require 'go-eldoc)
(add-hook 'go-mode-hook 'go-eldoc-setup)
(set-face-attribute 'eldoc-highlight-function-argument nil
                    :underline t :foreground "darkgreen"
                    :weight 'bold)
#+END_SRC
** auto-complete
#+BEGIN_SRC emacs-lisp
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories (concat GO_PKG_PATH "/src/github.com/auto-complete/auto-complete/dict"))
(require 'go-autocomplete)
(ac-config-default)
(ac-set-trigger-key "TAB")
#+END_SRC
** go-direx
#+BEGIN_SRC emacs-lisp
(define-key go-mode-map [f5] 'go-direx-pop-to-buffer)
#+END_SRC
* Python
** jedi
#+begin_src emacs-lisp
(add-hook 'python-mode-hook 
          (lambda()
             (jedi:setup)
             (add-hook 'before-save-hook 'pyimport-remove-unused)
          ))
(setq jedi:complete-on-dot t)                 ; optional
#+end_src
* Java
** maghanada
#+BEGIN_SRC emacs-lisp
(require 'meghanada)
(add-hook 'java-mode-hook
          (lambda ()
            ;; meghanada-mode on
            (meghanada-mode t)
            (add-hook 'before-save-hook 'meghanada-code-beautify-before-save)))
#+END_SRC
** jsp
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.jsp\\'" . html-mode))
#+end_src
** Eclim
#+BEGIN_SRC emacs-lisp
;;(custom-set-variables
;;  '(eclim-eclipse-dirs '("~/eclipse"))
;;  '(eclim-executable "~/eclipse/eclim")
;;  '(eclimd-executable "~/eclipse/eclimd"))
;;(require 'eclim)
;;(require 'eclimd)
;;(global-eclim-mode)
;;(setq help-at-pt-display-when-idle t)
;;(setq help-at-pt-timer-delay 0.1)
;;(help-at-pt-set-timer)
#+END_SRC
* jsx
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . jsx-mode))
(autoload 'jsx-mode "jsx-mode" "JSX mode" t)
#+end_src
* pdf-tools
#+BEGIN_SRC emacs-lisp
(pdf-tools-install)
#+END_SRC
* hql
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.hql\\'" . sql-mode))
#+END_SRC
* Auctex(disabled)
#+begin_src emacs-lisp
;; auctex
;; (load "auctex.el" nil t t)
;; (load "preview-latex.el" nil t t)
;;(setq TeX-output-view-style
;;      (quote
;;       (("^pdf$" "." "evince -f %o")
;;        ("^html?$" "." "google-chrome-stable %o"))))
#+end_src
* ecb(disabled)
#+begin_src emacs-lisp
;;'(require 'ecb-autoloads)
#+end_src
* Smex(disabled)
#+BEGIN_SRC emacs-lisp
;;(smex-initialize)
;;(global-set-key (kbd "M-x") 'smex)
;;(global-set-key (kbd "M-X") 'smex-major-mode-commands)
;;(require 'smex)
#+END_SRC
* Ido(disabled)
#+BEGIN_SRC emacs-lisp
;;(ido-mode 1)
;;(ido-everywhere 1)
;;(require 'ido-ubiquitous)
;;(ido-ubiquitous-mode 1)
#+END_SRC
